/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-dim": "#5e530f",
        "on-error-container": "#671200",
        "outline": "#787c73",
        "secondary-fixed": "#b1feda",
        "tertiary-dim": "#813f41",
        "on-surface": "#30342c",
        "on-primary-fixed": "#493f00",
        "on-primary-container": "#5c520d",
        "error-dim": "#821a01",
        "inverse-on-surface": "#9c9d97",
        "outline-variant": "#b0b3a9",
        "primary-fixed": "#f3e391",
        "error": "#aa371c",
        "secondary-fixed-dim": "#a3efcd",
        "secondary-container": "#b1feda",
        "surface": "#fafaf3",
        "primary-container": "#f3e391",
        "error-container": "#fa7150",
        "surface-container": "#edefe6",
        "tertiary-container": "#fba4a4",
        "surface-tint": "#6a5f1b",
        "tertiary-fixed": "#fba4a4",
        "surface-variant": "#e1e4d9",
        "tertiary-fixed-dim": "#ec9797",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e4d9",
        "tertiary": "#904b4c",
        "surface-container-high": "#e7e9df",
        "on-secondary": "#e5fff0",
        "surface-container-low": "#f3f4ec",
        "background": "#fafaf3",
        "secondary-dim": "#075f44",
        "surface-dim": "#d8dcd0",
        "on-secondary-container": "#12644a",
        "on-secondary-fixed-variant": "#216f53",
        "on-primary": "#fff8e8",
        "primary": "#6a5f1b",
        "on-primary-fixed-variant": "#675c17",
        "on-tertiary-container": "#602628",
        "on-tertiary": "#fff7f6",
        "inverse-primary": "#ffef9b",
        "surface-bright": "#fafaf3",
        "on-tertiary-fixed": "#441014",
        "on-surface-variant": "#5c6058",
        "inverse-surface": "#0d0f0b",
        "on-secondary-fixed": "#005139",
        "on-background": "#30342c",
        "primary-fixed-dim": "#e5d584",
        "on-tertiary-fixed-variant": "#6b2e30",
        "on-error": "#fff7f6",
        "secondary": "#1c6b50"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
